### PR TITLE
Allow Factory build methods

### PR DESCRIPTION
**Pull request by m7moud**
This change allows build methods in factories.

### CODE REVIEW

**Comment by dereuromark** [comment]
can u outline the change reason in your description please? we will talk about this tomorrow in AA

**Comment by dereuromark** [comment]
ping @m7moud

**Comment by dereuromark** [comment]
the new() inside here is wrong and should be its own method.
but yeah, chaining here seems to have the need for build word.

**Comment by dereuromark** [comment]
See this factory:
```php
    /**
     * @return \Spryker\Zed\DataImport\Business\Model\DataImporterInterface
     */
    public function getCartDataImport(): DataImporterInterface
    {
        $dataImporter = $this->getCsvDataImporterFromConfig(
            $this->getConfig()->getMultiCartDataImporterConfiguration()
        );

        $dataSetStepBroker = $this->createTransactionAwareDataSetStepBroker();
        $dataSetStepBroker->addStep($this->createAddLocalesStep())
            ->addStep($this->createCustomerReferenceValidationStep())
            ->addStep($this->createStoreToIdStoreStep())
            ->addStep($this->createCartWriterStep());

        $dataImporter->addDataSetStepBroker($dataSetStepBroker);

        return $dataImporter;
    }
```

should then be

```php
    /**
     * @return \Spryker\Zed\DataImport\Business\Model\DataImporterInterface
     */
    public function buildCartDataImport(): DataImporterInterface
    {
        $dataImporter = $this->getCsvDataImporterFromConfig(
            $this->getConfig()->getMultiCartDataImporterConfiguration()
        );

        $dataSetStepBroker = $this->createTransactionAwareDataSetStepBroker();
        $dataSetStepBroker->addStep($this->createAddLocalesStep())
            ->addStep($this->createCustomerReferenceValidationStep())
            ->addStep($this->createStoreToIdStoreStep())
            ->addStep($this->createCartWriterStep());

        $dataImporter->addDataSetStepBroker($dataSetStepBroker);

        return $dataImporter;
    }
```
when containing `->add` calls.

**Comment by m7moud** [comment]
Exactly, that's what we discussed and that's what we agreed on :D

The new() inside the method is wrong but it's enforced because the method prefixed with create should have a `new` statement.

Should I resolve the conflict here?

**Comment by dereuromark** [comment]
We decided to not do that, they must always be called "get()".
Please make sure there is no "new ..." inside, as that violates the architecture

**Pull request closed without merging**
