### PR TITLE
Clean up old rules, which already moved to common

### PR DESCRIPTION
**Pull request by RodinVasily**
Issue #27 

These rules seem to be copy paste for rules, which already exist in common.
However, I noticed small condition in `\ArchitectureSniffer\Common\Factory\AbstractFactoryRule`
```
        // Factories in persistence layer have other rules
        if (strpos($className, '\\Persistence\\') !== false) {
            return false;
        }
```
Is it still a thing? Should we remove it as well?

Fun fact: regexp in `\ArchitectureSniffer\Zed\Persistence\Factory` doesn't cover persistence layer

### CODE REVIEW

**Comment by RodinVasily** [comment]
@rklatt any addition about my question in PR description?

**Comment by stereomon** [comment]
I think you can remove it when you make the pattern more explicit to only match for (Communication|Business)Factory

**Comment by RodinVasily** [comment]
ah, I see why `Persistence` factories are different, because they mostly have methods with static method call instead of `new`. So then let's leave it as it is.

**Comment by dereuromark** [comment]
@RodinVasily What do you mean? Should this still be merged? Anything missing?

**Comment by RodinVasily** [comment]
@dereuromark All good, this PR can be merged. Sorry for not clear message. I've just tried to understand what to do with Persistence factories.

**Pull request merged**
